version: '3.8'

services:
  # Config Server Replica Set
  configsvr1:
    image: mongo:6.0
    container_name: configsvr1
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    volumes:
      - ./data/config1:/data/db
    ports:
      - "27019:27019"

  configsvr2:
    image: mongo:6.0
    container_name: configsvr2
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    volumes:
      - ./data/config2:/data/db

  configsvr3:
    image: mongo:6.0
    container_name: configsvr3
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    volumes:
      - ./data/config3:/data/db

  # Shard 1 Replica Set
  shard1a:
    image: mongo:6.0
    container_name: shard1a
    command: mongod --shardsvr --replSet shard1ReplSet --port 27117 --bind_ip_all
    volumes:
      - ./data/shard1a:/data/db
    ports:
      - "27117:27117"

  shard1b:
    image: mongo:6.0
    container_name: shard1b
    command: mongod --shardsvr --replSet shard1ReplSet --port 27118 --bind_ip_all
    volumes:
      - ./data/shard1b:/data/db

  shard1c:
    image: mongo:6.0
    container_name: shard1c
    command: mongod --shardsvr --replSet shard1ReplSet --port 27119 --bind_ip_all
    volumes:
      - ./data/shard1c:/data/db

  # Shard 2 Replica Set
  shard2a:
    image: mongo:6.0
    container_name: shard2a
    command: mongod --shardsvr --replSet shard2ReplSet --port 27217 --bind_ip_all
    volumes:
      - ./data/shard2a:/data/db
    ports:
      - "27217:27217"

  shard2b:
    image: mongo:6.0
    container_name: shard2b
    command: mongod --shardsvr --replSet shard2ReplSet --port 27218 --bind_ip_all
    volumes:
      - ./data/shard2b:/data/db

  shard2c:
    image: mongo:6.0
    container_name: shard2c
    command: mongod --shardsvr --replSet shard2ReplSet --port 27219 --bind_ip_all
    volumes:
      - ./data/shard2c:/data/db

  # Shard 3 Replica Set
  shard3a:
    image: mongo:6.0
    container_name: shard3a
    command: mongod --shardsvr --replSet shard3ReplSet --port 27317 --bind_ip_all
    volumes:
      - ./data/shard3a:/data/db
    ports:
      - "27317:27317"

  shard3b:
    image: mongo:6.0
    container_name: shard3b
    command: mongod --shardsvr --replSet shard3ReplSet --port 27318 --bind_ip_all
    volumes:
      - ./data/shard3b:/data/db

  shard3c:
    image: mongo:6.0
    container_name: shard3c
    command: mongod --shardsvr --replSet shard3ReplSet --port 27319 --bind_ip_all
    volumes:
      - ./data/shard3c:/data/db

  # mongos Query Router
  mongos:
    image: mongo:6.0
    container_name: mongos
    depends_on:
      - configsvr1
      - configsvr2
      - configsvr3
      - shard1a
      - shard1b
      - shard1c
      - shard2a
      - shard2b
      - shard2c
      - shard3a
      - shard3b
      - shard3c
    command: >
      mongos --configdb configReplSet/configsvr1:27019,configsvr2:27019,configsvr3:27019
            --bind_ip_all --port 27020
    ports:
      - "27020:27020"
